spring:
  #以下为druid 数据库连接池配置
  datasource:
    #springboot 目前默认使用的数据库连接池有
     # org.apache.tomcat.jdbc.pool.DataSource,
     # com.zaxxer.hikari.HikariDataSource,
     # org.apache.commons.dbcp.BasicDataSource,
     # org.apache.commons.dbcp2.BasicDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    name: DataSource-A
    url: jdbc:mysql://47.98.158.193:3306/study?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true&amp;autoReconnect=true;useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 8
    minIdle: 5
    maxWait: 50
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxOpenPreparedStatements: -1
    validationQuery: SELECT 1
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 1:Destroy线程会检测连接的间隔时间2:testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 以下为springboot jpa的配置
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        #hibernate方言配置
        dialect: org.hibernate.dialect.MySQLDialect
    #是否注册OpenEntityManagerInViewInterceptor，绑定JPA EntityManager到请求线程中，默认为: true
    open-in-view: false
    database-platform:
  session:
    store-type: none

# 以下为druid 监控配置
druid:
  stat:
    view:
      #ip白名单
      allow: 127.0.0.1
      #ip黑名单
      deny: 192.168.1.2
      #登录账号
      loginUsername: root
      #登录密码
      loginPassword: root
      #是否重置密码
      resetEnable: true
    filter:
      urlPatterns: /*
security:
  basic:
    enabled: false

zeus:
  browser:
    login-page: /demo-login.html
  social:
    qq:
      appId: 123
      appSecret: 123